# PCA for dimensionality reduction

In [1]:
import numpy as np
xdata = np.array([[0, 4], 
                  [1, 3],
                  [2, 2], 
                  [3, 1],
                  [4, 0]])  #5 x 2的矩陣

X0 = xdata[:,0]  #第一行
X1 = xdata[:,1]  #第二行
x_cov = np.cov(xdata.T)  #xdata.T為轉置矩陣,然後計算協方差cov
print("cov：")
print(x_cov)
w, v = np.linalg.eig(np.array(x_cov))  #計算特徵值和特徵向量
print("特徵值：")
print(w)  #特徵值
print("特徵向量：")
print(v)  #特徵向量
a = v[:,0]  #取特徵向量第一行的值
a = a.reshape(2,1)  #變成2 x 1的矩陣
ans = np.matmul(xdata,a)  #xdata和特徵向量相乘即是降維後的結果
print("降維後的結果：")
print(ans)

cov：
[[ 2.5 -2.5]
 [-2.5  2.5]]
特徵值：
[5.0000000e+00 4.4408921e-16]
特徵向量：
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
降維後的結果：
[[-2.82842712e+00]
 [-1.41421356e+00]
 [ 2.22044605e-16]
 [ 1.41421356e+00]
 [ 2.82842712e+00]]
